name: Test Pulsar Package
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # , windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the Latest Package Code
        uses: actions/checkout@v3
      - name: Setup Pulsar Editor
        uses: pulsar-edit/action-pulsar-dependency@v3.4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies using ppm
        run: pulsar --package install
        working-directory: ./language-concat
      - name: Run the headless Pulsar Tests
        uses: coactions/setup-xvfb@v1.0.1
        with:
          run: pulsar --test ./language-concat/spec/
